name: Convert Github link to jsdelivr link
on:
  push:
    branches:
      - master
jobs:
  AUTOBOT:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Download script
      run: wget -c https://github.com/baddate/imagedb/raw/dev/auto.sh
    - name: Run script
      run:  bash auto.sh
    - name: Delete input
      run: rm -f input
    - name: Push
      run: |
          git config --global user.email "alexdemail@e.email"
          git config --global user.name "baddate"
          git add . && git commit -m "update" && git push
